### PR TITLE
Spring data

### PR DESCRIPTION
**Pull request by fiammara**

### CODE REVIEW

**Comment by Akayeshmantha** [comment]
Hi @fiammara  please squash your’e commits in to a one commit 🙂

**Comment by Akayeshmantha** [comment]
And make sure to resolve the conflict as well 😯.

Great work

**Comment by jamesbognar** [comment]
Changes are in.

**Comment by fiammara** [comment]
Thank you.

2019-10-14, pr, 17:02 James Bognar <notifications@github.com> rašė:

**Pull request merged**
