### PR TITLE
JUNEAU-152 Added a Dockerfile to run app using war file

### PR DESCRIPTION
**Pull request by ishita20**
The current Dockerfile has steps to only run the war file. Should I also add steps to build the app and use the war file from this build itself?

### CODE REVIEW

**Comment by jamesbognar** [comment]
Looks good!

**Comment by jamesbognar** [comment]
@ishita20 - 

"The current Dockerfile has steps to only run the war file. Should I also add steps to build the app and use the war file from this build itself?"  

Do you mean run maven from within the Dockerfile to produce the initial war file?

**Comment by ishita20** [comment]
Yes.

**Comment by jamesbognar** [comment]
It's an interesting idea.  I posted a feedback request on the dev channel.  Lets see what others have to say.

**Pull request merged**
